name: "⛑ Debug manifests ⛑"
description: "Debug some kubernetes manifests"
inputs:
  token:
    description: "Github token for PR comment"
  path:
    description: "Manifests file path, default manifests.yaml"
    default: "manifests.yaml"
  name:
    description: "Manifests artifact name"
    default: "manifests.yaml"
  provider:
    description: "Plateform provider"

outputs:
  markdown-json:
    description: "debug manifests markdown wrapped by json"
    value: ${{ steps.debug-manifests-output.outputs.markdown-json }}
  manifests-images:
    description: "docker images manifests from manifests as json format"
    value: ${{ steps.debug-manifests-output.outputs.manifests-images }}

runs:
  using: "composite"
  steps:
    - name: Archive manifest
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}

    - name: Debug manifests
      id: debug-manifests-output
      uses: socialgouv/workflows/actions/debug-manifests/output@v1
      with:
        path: ${{ inputs.path }}
        provider: ${{ inputs.provider }}