on:
  push:
    branches:
      - "**"
    tags-ignore:
      - v*

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.ref }}

jobs:
  kontinuous:
    uses: socialgouv/workflows/.github/workflows/use-ks-wh-review.yaml@master
    secrets: inherit
