name: "Trivy Scan on manifests"
description: "Scan docker image present in kubernetes manifests for security issues"
inputs:
  image:
    description: "docker image ref"
    required: true
  token:
    description: "The Github authentication token"
    required: true
  severity:
    description: "Trivy level of security"
    default: "CRITICAL"

runs:
  using: "composite"
  steps:
    - name: Run Trivy vulnerability scanner
      continue-on-error: true
      timeout-minutes: 20
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ inputs.image }}'
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: '${{ intpus.severity }}'
        

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'
        token: '${{ inputs.token }}'