name: "Trivy Scan on manifests"
description: "Scan docker image present in kubernetes manifests for security issues"
inputs:
  image:
    description: "docker image ref"
    required: true
  token:
    description: "The Github authentication token"
    required: true
  severity:
    description: "Trivy level of security"
    default: "CRITICAL"
  vuln-type:
    description: "Trivy type of vuln. ex: os,library"
    default: "os"
  config:
    description: "Trivy additional config from file"
    default: "trivy.yaml"
    
runs:
  using: "composite"
  steps:
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ inputs.image }}'
        severity: '${{ inputs.severity }}'  
        exit-code: '1'
        timeout: "20m"
        vuln-type: '${{ inputs.vuln-type }}' 
        trivy-config: '${{ inputs.config }}'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    - uses: actions/upload-artifact@v3
      with:
        name: trivy-results
        path: trivy-results.sarif
        
    - name:
      shell: bash
      run: |
        ls -la
        
    # - name: Checkout repository
    #   uses: actions/checkout@v3

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'
        token: '${{ inputs.token }}'
