name: 🔨 Build Docker Image

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment name for GitHub environment context'
        required: true
        type: string
      image-name:
        description: 'Docker image name (e.g., app, hasura, api)'
        required: true
        type: string
      # Build configuration
      path:
        description: 'Root directory'
        required: false
        type: string
        default: '.'
      context:
        description: 'Build context path'
        required: false
        type: string
        default: '.'
      dockerfile:
        description: 'Dockerfile path'
        required: false
        type: string
        default: 'Dockerfile'
      platforms:
        description: 'Platform(s) for multi-arch builds (e.g., linux/amd64,linux/arm64)'
        required: false
        type: string
        default: 'linux/amd64'
      target:
        description: 'Build stage to build (for multi-stage Dockerfiles)'
        required: false
        type: string
        default: ''
      push:
        description: 'Whether to push to registry'
        required: false
        type: string
        default: 'true'
      build-args:
        description: 'Build arguments as multiline string'
        required: false
        type: string
        default: ''
      secrets:
        description: 'Build secrets as multiline string'
        required: false
        type: string
        default: ''
      # Registry configuration
      registry:
        description: 'Docker registry URL'
        required: false
        type: string
        default: ''
      registry-username:
        description: 'Registry username'
        required: false
        type: string
        default: ''
      registry-password:
        description: 'Registry password'
        required: false
        type: string
        default: ''
      # Buildkit daemon configuration
      buildkit-daemon-address:
        description: 'Address of the buildkit daemon'
        required: false
        type: string
        default: ''
      buildkit-cert-ca:
        description: 'Buildkit CA certificate content'
        required: false
        type: string
        default: ''
      buildkit-cert:
        description: 'Buildkit certificate content'
        required: false
        type: string
        default: ''
      buildkit-cert-key:
        description: 'Buildkit certificate key content'
        required: false
        type: string
        default: ''
      buildkit-svc-count:
        description: 'Number of buildkit services for modulo distribution'
        required: false
        type: string
        default: ''
      buildkit-service-enabled:
        description: 'Toggle buildkit service usage'
        required: false
        type: string
        default: 'true'
      buildkit-version:
        description: 'Buildkit version to use'
        required: false
        type: string
        default: 'v0.22.0'
      # Cache configuration
      cache-enabled:
        description: 'Enable build cache'
        required: false
        type: string
        default: 'true'
      cache-from-refs:
        description: 'Additional cache references to import from (comma separated)'
        required: false
        type: string
        default: ''
      cache-to-refs:
        description: 'Additional cache references to export to (comma separated)'
        required: false
        type: string
        default: ''
      git-default-branch:
        description: 'Default git branch for caching'
        required: false
        type: string
        default: 'main'
      # Advanced options
      fallback-enabled:
        description: 'Enable fallback to local buildkit when service unavailable'
        required: false
        type: string
        default: 'false'
    outputs:
      tags:
        description: 'Docker image tags'
        value: ${{ jobs.build.outputs.tags }}
      labels:
        description: 'Docker image labels'
        value: ${{ jobs.build.outputs.labels }}

jobs:
  build:
    environment: ${{ inputs.environment }}
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
    runs-on: ubuntu-latest
    steps:
      - name: ⏬ Checkout code repository
        uses: actions/checkout@v4

      - name: 📌 Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.registry || vars.REGISTRY_URL }}/${{ vars.PROJECT_NAME }}/${{ github.event.repository.name }}/${{ inputs.image-name }}
          tags: |
            type=semver,pattern=v{{version}},priority=900
            type=raw,value=preprod-{{sha}},enable=${{ github.ref == 'refs/heads/preprod' }},priority=850
            type=raw,value=persist-{{sha}},enable=${{ 
              github.ref_name == 'dev' || 
              github.ref_name == 'develop' || 
              github.ref_name == 'preprod' || 
              github.ref_name == 'main' || 
              github.ref_name == 'master'
            }},priority=840
            type=sha,prefix=sha-,format=long,priority=890
            type=ref,event=branch,priority=600
            type=ref,event=pr,priority=600
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }},priority=200

      - name: 📦 Build and push Docker image for ${{ inputs.image-name }}
        uses: socialgouv/workflows/actions/buildkit@v1
        with:
          path: ${{ inputs.path }}
          context: ${{ inputs.context }}
          dockerfile: ${{ inputs.dockerfile }}
          platforms: ${{ inputs.platforms }}
          target: ${{ inputs.target }}
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          registry: ${{ inputs.registry || vars.REGISTRY_URL }}
          registry-username: ${{ inputs.registry-username || secrets.REGISTRY_USERNAME }}
          registry-password: ${{ inputs.registry-password || secrets.REGISTRY_PASSWORD }}
          buildkit-daemon-address: ${{ inputs.buildkit-daemon-address || vars.BUILDKIT_DAEMON_ADDRESS }}
          buildkit-cert-ca: ${{ inputs.buildkit-cert-ca || secrets.BUILDKIT_CERT_CA }}
          buildkit-cert: ${{ inputs.buildkit-cert || secrets.BUILDKIT_CERT }}
          buildkit-cert-key: ${{ inputs.buildkit-cert-key || secrets.BUILDKIT_CERT_KEY }}
          buildkit-svc-count: ${{ inputs.buildkit-svc-count || vars.BUILDKIT_SVC_COUNT }}
          buildkit-service-enabled: ${{ inputs.buildkit-service-enabled }}
          buildkit-version: ${{ inputs.buildkit-version }}
          cache-enabled: ${{ inputs.cache-enabled }}
          cache-from-refs: ${{ inputs.cache-from-refs }}
          cache-to-refs: ${{ inputs.cache-to-refs }}
          git-default-branch: ${{ inputs.git-default-branch }}
          fallback-enabled: ${{ inputs.fallback-enabled }}
          build-args: ${{ inputs.build-args }}
          secrets: ${{ inputs.secrets }}
