on:
  workflow_call:
    inputs:
      webhookUri:
        required: false
        type: string
      triggerWebhook:
        required: false
        type: boolean
        default: true
    secrets:
      KUBEWEBHOOK_TOKEN:
        required: true

jobs:
  deploy:
    name: Review Pipeline 👀
    runs-on: ubuntu-latest
    environment: review
    steps:
      - uses: socialgouv/workflows/actions/deployment-starting@v1
        id: deployment-starting
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment-scope: review

      - uses: socialgouv/kontinuous/.github/actions/deploy-via-webhook@next-workflows/deploy-via-github-improved
        continue-on-error: true
        with:
          webhookToken: ${{ secrets.KUBEWEBHOOK_TOKEN }}
          webhookUri: ${{ inputs.webhookUri }}
          triggerWebhook: ${{ inputs.triggerWebhook }}
          environment: dev
      
      - uses: socialgouv/workflows/actions/deployment-ending@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          deployment-id: ${{ steps.deployment-starting.outputs.deployment-id }}
          deployment-name: ${{ steps.deployment-starting.outputs.deployment-name }}