on:
  workflow_call:
    inputs:
      webhookUri:
        required: false
        type: string
      triggerWebhook:
        required: false
        type: boolean
        default: true
      chart:
        required: false
        type: string
      ignoreProjectTemplates:
        required: false
        type: boolean
      environment:
        required: false
        type: string
      inlineValues:
        required: false
        type: string
      inlineSet:
        required: false
        type: string
    secrets:
      KUBEWEBHOOK_TOKEN:
        required: true

jobs:
  deploy:
    name: Custom Pipeline 🛸
    runs-on: ubuntu-latest
    steps:
      - uses: socialgouv/kontinuous/.github/actions/deploy-via-webhook@v1
        with:
          webhookToken: ${{ secrets.KUBEWEBHOOK_TOKEN }}
          webhookUri: ${{ inputs.webhookUri }}
          triggerWebhook: ${{ inputs.triggerWebhook }}
          chart: ${{ inputs.chart }}
          ignoreProjectTemplates: ${{ inputs.ignoreProjectTemplates }}
          environment: ${{ inputs.environment }}
          inlineValues: ${{ inputs.inlineValues }}
          inlineSet: ${{ inputs.inlineSet }}
          projectName: ${{ vars.projectName }}