on:
  workflow_call:
    inputs:
      webhookUri:
        required: false
        type: string
      triggerWebhook:
        required: false
        type: boolean
        default: true
      ignoreProjectTemplates:
        required: false
        default: true
        type: boolean
      inlineValues:
        required: false
        type: string
      inlineSet:
        required: false
        type: string
    secrets:
      KUBEWEBHOOK_TOKEN:
        required: true

jobs:
  deploy:
    name: Deactivate Pipeline ♻️
    runs-on: ubuntu-latest
    steps:
      - uses: socialgouv/kontinuous/.github/actions/deploy-via-webhook@v1
        continue-on-error: true
        with:
          webhookToken: ${{ secrets.KUBEWEBHOOK_TOKEN }}
          webhookUri: ${{ inputs.webhookUri }}
          triggerWebhook: ${{ inputs.triggerWebhook }}
          chart: deactivate
          ignoreProjectTemplates: ${{ inputs.ignoreProjectTemplates }}
          inlineValues: ${{ inputs.inlineValues }}
          inlineSet: ${{ inputs.inlineSet }}
          environment: dev
      
      - name: Load Deployment Vars
        id: deployment-vars
        shell: bash
        run: |
          set -e
          ENVIRONMENT_SCOPE=review
          BRANCH=$(node -e "const githubEvent = JSON.parse(fs.readFileSync('$GITHUB_EVENT_PATH'));const ref = githubEvent.ref || githubEvent.pull_request?.head?.ref || '' ;process.stdout.write(ref);")
          BRANCH=${BRANCH#refs/heads/}
          BRANCH=${BRANCH#refs/tags/}
          BRANCH_SLUG=$(npx @socialgouv/env-slug "$BRANCH")
          deployment_name="${ENVIRONMENT_SCOPE}-${BRANCH_SLUG}"
          echo "deployment-name=$deployment_name">>$GITHUB_OUTPUT

      - name: Clean deployment
        uses: socialgouv/deployments@v1
        with:
          step: deactivate-env
          token: ${{ secrets.GITHUB_TOKEN }}
          env: ${{ steps.deployment-vars.outputs.deployment-name }}
          desc: Deployment was pruned
      
      - name: Clean review sub environment
        uses: socialgouv/deployments@v1
        with:
          step: delete-env
          token: ${{ secrets.SOCIALGROOVYBOT_BOTO_PAT }}
          env: ${{ steps.deployment-vars.outputs.deployment-name }}
          desc: Environment was pruned