on:
  workflow_call:
    secrets:
      KUBECONFIG:
        required: true

jobs:
  deploy:
    name: PreProduction Pipeline 😎
    runs-on: ubuntu-latest
    environment: preproduction
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: socialgouv/workflows/actions/deployment-starting@v1
        id: deployment-starting
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment-scope: preproduction

      - uses: socialgouv/kontinuous/.github/actions/deploy-via-github@next-workflows
        id: deployment
        continue-on-error: true
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          environment: preprod
      
      - uses: socialgouv/workflows/actions/deployment-ending@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          deployment-id: ${{ steps.deployment-starting.outputs.deployment-id }}
          deployment-name: ${{ steps.deployment-starting.outputs.deployment-name }}
          deployment-ok: ${{ steps.deployment.outcome == 'success' && 'true' || 'false' }}